[package]
name = "execve"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
goblin = "0.8.2"
libc = "0.2.155"
log = "0.4.21"
env_logger = "0.11.3"
nix = { version = "0.28.0", features = ["mman"] }
memmap2 = "0.9.4"
