[package]
name = "execve"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
nix = { version = "0.30.1", features = ["fs", "mman"] }


[build-dependencies]
cc = "1.2.29"

[dev-dependencies]
tempfile = "3.20.0"
