[package]
name = "fspy"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
futures-util = "0.3.31"
libc = "0.2.171"
linux-raw-sys = { version = "0.9.4", features = ["ptrace"] }
# async-send-fd = { version = "1.2.0", features = ["tokio"] }
passfd = "0.1.6"
tokio = { version = "1.44.2", features = ["net", "process", "io-util", "sync"]}
which = "7.0.3"

[target.'cfg(target_os= "linux")'.dependencies]
tokio-seqpacket = "0.8.0"
nix = { version = "0.29.0", features = ["fs", "process", "socket"] }

[dev-dependencies]
tokio = { version = "*", features = ["rt", "macros"] }

# [profile.release]
# lto = true
# codegen-units = 1
