/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    pub fn reflect_execves(
        elf: *const ::std::os::raw::c_uchar,
        argv: *mut *mut ::std::os::raw::c_char,
        env: *mut *mut ::std::os::raw::c_char,
        stack: *mut usize,
    );
}
unsafe extern "C" {
    pub fn reflect_execv(
        elf: *const ::std::os::raw::c_uchar,
        argv: *mut *mut ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn reflect_execve(
        elf: *const ::std::os::raw::c_uchar,
        argv: *mut *mut ::std::os::raw::c_char,
        env: *mut *mut ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn reflect_mfd_execv(
        elf: *const ::std::os::raw::c_uchar,
        argv: *mut *mut ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn reflect_mfd_execve(
        elf: *const ::std::os::raw::c_uchar,
        argv: *mut *mut ::std::os::raw::c_char,
        env: *mut *mut ::std::os::raw::c_char,
    );
}
