[package]
name = "fspy_e2e"
version = "0.0.0"
publish = false
edition.workspace = true

[dependencies]
fspy = { workspace = true }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"
tokio = { version = "1.47.1", features = ["full"] }
futures-util = "0.3.31"
