[build]
target = "x86_64-unknown-linux-musl" # make rust-analyser work on non-linux os
target-dir = "../../target/fspy_linux_execve_host_target" 

[target.'cfg(target_env = "musl")']
linker = "rust-lld"
rustflags = ["-Ctarget-feature=+crt-static", "-Crelocation-model=pic", "-Clink-args=--no-dynamic-linker"]
