[build]
target-dir = "../../target/fspy_linux_execve_host_target" 

[target."x86_64-unknown-linux-musl"]
linker = "rust-lld"
rustflags = ["-Ctarget-feature=+crt-static", "-Crelocation-model=pic", "-Clink-args=--no-dynamic-linker"]

[target."aarch64-unknown-linux-musl"]
linker = "rust-lld"
rustflags = ["-Ctarget-feature=+crt-static", "-Crelocation-model=pic", "-Clink-args=--no-dynamic-linker"]
