[build]
target-dir = "../../target/fspy_linux_execve_host_target" 

[target.'cfg(target_env = "musl")']
linker = "rust-lld"
rustflags = ["-Ctarget-feature=+crt-static", "-Crelocation-model=pic", "-Clink-args=--no-dynamic-linker"]
