[package]
name = "preload_cdylib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# empty `[workspace]` table to keep this package out of the workspace
[workspace]
