name: Test

on:
    workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04-arm
            shell: bash
          - os: ubuntu-22.04
            shell: bash
          - os: windows-2025
            shell: wsl-bash {0}
          # WSL not working on windows arm: https://github.com/actions/partner-runner-images/issues/109
          # - os: windows-11-arm
          #   shell: wsl-bash {0}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
    - uses: actions/checkout@v4
    - uses: Vampire/setup-wsl@v6
      with:
        distribution: Ubuntu-22.04
        wsl-shell-command: bash -i -euo pipefail # load .profile in each step
        additional-packages:
          curl
          build-essential
          pkg-config
          libssl-dev
      if: runner.os == 'Windows'
    - name: Install rust in WSL
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none
        echo "export CARGO_TARGET_DIR=$HOME/target" >> ~/.bashrc # Set a consistent target directory on the native WSL filesystem
      if: runner.os == 'Windows'
    - name: Build
      run: |
        rustup show
        cargo test --no-run --workspace
    - name: Test
      run: |
        uname -a
        RUST_LOG_SPAN_EVENTS=full RUST_LOG=trace cargo test --workspace --all-features -- --nocapture
