name: Test

on:
    workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # - os: ubuntu-22.04-arm
          #   shell: bash
          # - os: ubuntu-22.04
          #   shell: bash
          - os: windows-2025
            shell: bash
          # WSL not working properly: https://github.com/actions/partner-runner-images/issues/109
          # - os: windows-11-arm
          #   shell: wsl-bash {0}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
    - uses: actions/checkout@v4
    - uses: Vampire/setup-wsl@v6
      with:
        distribution: Ubuntu-22.04
        cache: false
      if: runner.os == 'Windows'
    - name: Install rust in WSL
      run: |
        sudo apt-get update -y
        sudo apt-get install -y curl build-essential
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none # https://github.com/rust-lang/rustup/issues/297#issuecomment-589949164
      if: runner.os == 'Windows'
    - name: Build
      run: |
        # temp fix for setup-wsl's bash not loading .profile by default:
        # https://github.com/Vampire/setup-wsl/blob/6819906081f7afebe0cfc34e838b6f8405045672/README.md#wsl-shell-command
        . "$HOME/.cargo/env"
        rustup show
        cargo test --no-run --workspace
    - name: Test
      run: |
        . "$HOME/.cargo/env"
        cargo test --workspace
